# Generated by Django 2.2.28 on 2022-10-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221005_1638'),
        ('users', '0004_auto_20221004_1345'),
    ]

    operations = [
    ]
