# Generated by Django 4.1.2 on 2022-10-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name'),
        ('users', '0006_remove_user_confirmation_code'),
    ]

    operations = [
    ]
